create table if not exists public.apostila_image_review_queue (
  id bigint generated by default as identity primary key,
  apostila_path text not null,
  apostila_title text,
  candidate_key text not null,
  target_section text not null,
  target_selector text,
  placement text not null default 'after' check (placement in ('after','before','append','prepend')),
  proposed_asset jsonb not null default '{}'::jsonb,
  source_url text not null,
  source_name text,
  source_license text,
  source_trust text not null default 'unverified',
  review_status text not null default 'pending' check (review_status in ('pending','approved')),
  reviewed_by uuid,
  reviewed_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (apostila_path, candidate_key)
);

create index if not exists apostila_image_review_queue_path_status_idx
  on public.apostila_image_review_queue (apostila_path, review_status, created_at);

alter table public.apostila_image_review_queue enable row level security;

drop policy if exists "apostila_images_select" on public.apostila_image_review_queue;
create policy "apostila_images_select"
  on public.apostila_image_review_queue
  for select
  to anon, authenticated
  using (review_status = 'approved' or public.is_admin());

drop policy if exists "apostila_images_admin_insert" on public.apostila_image_review_queue;
create policy "apostila_images_admin_insert"
  on public.apostila_image_review_queue
  for insert
  to authenticated
  with check (public.is_admin());

drop policy if exists "apostila_images_admin_update" on public.apostila_image_review_queue;
create policy "apostila_images_admin_update"
  on public.apostila_image_review_queue
  for update
  to authenticated
  using (public.is_admin())
  with check (public.is_admin());

drop policy if exists "apostila_images_admin_delete" on public.apostila_image_review_queue;
create policy "apostila_images_admin_delete"
  on public.apostila_image_review_queue
  for delete
  to authenticated
  using (public.is_admin());

create or replace function public.admin_review_apostila_image(
  p_id bigint,
  p_decision text
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_row public.apostila_image_review_queue%rowtype;
begin
  if not public.is_admin() then
    raise exception 'Acesso administrativo necessário';
  end if;

  if p_decision = 'approved' then
    update public.apostila_image_review_queue
       set review_status = 'approved',
           reviewed_by = auth.uid(),
           reviewed_at = now(),
           updated_at = now()
     where id = p_id
     returning * into v_row;

    if v_row.id is null then
      raise exception 'Imagem candidata não encontrada';
    end if;

    return jsonb_build_object('id', v_row.id, 'status', 'approved');
  elsif p_decision = 'rejected' then
    delete from public.apostila_image_review_queue
     where id = p_id
     returning * into v_row;

    if v_row.id is null then
      raise exception 'Imagem candidata não encontrada';
    end if;

    return jsonb_build_object('id', v_row.id, 'status', 'deleted');
  else
    raise exception 'Decisão inválida';
  end if;
end;
$$;

grant execute on function public.admin_review_apostila_image(bigint,text) to authenticated;
